;;;; Autogenerated ASD file for system "DYNOTUNE.TEST"
;;;; In order to regenerate it, run update-asdf
;;;; from shell (see https://github.com/phoe-krk/asd-generator)
;;;; For those who do not have update-asdf,
;;;; run `ros install asd-generator` (if you have roswell installed)
;;;; There are also an interface available from lisp:
;;;; (asd-generator:regen &key im-sure)
(defsystem dynotune.test
 :author "Masataro Asai"
 :mailto "guicho2.71828@gmail.com"
 :description "Test system of dynotune"
 :license "LLGPL"
 :depends-on (:dynotune
              :fiveam
              :named-readtables)
 :serial t
 :pathname "t/"
 :components ((:file "package")
              (:file "continuous"))
 :perform (test-op :after (op c)
           (eval
            (read-from-string "(let ((res (5am:run :dynotune)))
     (explain! res)
     (every #'fiveam::TEST-PASSED-P res))"))))
